In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid Activation Function
def sigmoid_derivative(x):
    return x * (1 - x)

# Neural Network Class Definition
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.bias_hidden = np.random.randn(1, self.hidden_size)
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        self.bias_output = np.random.randn(1, self.output_size)

    def forward(self, X):
        self.input_layer = X
        self.hidden_layer_input = np.dot(self.input_layer, self.weights_input_hidden) + self.bias_hidden
        self.hidden_layer_output = sigmoid(self.hidden_layer_input)
        self.output_layer_input = np.dot(self.hidden_layer_output, self.weights_hidden_output) + self.bias_output
        self.output_layer_output = sigmoid(self.output_layer_input)
        return self.output_layer_output

    def backward(self, X, y, learning_rate):
        error_output = y - self.output_layer_output
        output_layer_delta = error_output * sigmoid_derivative(self.output_layer_output)
        error_hidden = output_layer_delta.dot(self.weights_hidden_output.T)
        hidden_layer_delta = error_hidden * sigmoid_derivative(self.hidden_layer_output)

        self.weights_hidden_output += self.hidden_layer_output.T.dot(output_layer_delta) * learning_rate
        self.bias_output += np.sum(output_layer_delta, axis=0, keepdims=True) * learning_rate
        self.weights_input_hidden += X.T.dot(hidden_layer_delta) * learning_rate
        self.bias_hidden += np.sum(hidden_layer_delta, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            self.forward(X)
            self.backward(X, y, learning_rate)
            if epoch % 1000 == 0:
                loss = np.mean(np.square(y - self.output_layer_output))
                print(f"Epoch {epoch} - Loss: {loss}")

# Main Program
if __name__ == "__main__":
    # Load the Iris dataset
    data = pd.read_csv("Iris.csv")
    X = data.iloc[:, 1:5].values  # Feature columns (Sepal/Petal length/width)
    y = data.iloc[:, 5].values    # Target column (Species)

    # Encode target labels to numeric values
    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)

    # One-hot encode the target labels
    one_hot_encoder = OneHotEncoder(sparse_output=False)  # Use sparse_output instead of sparse
    y = one_hot_encoder.fit_transform(y.reshape(-1, 1))

    # Standardize the features
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Create an instance of the NeuralNetwork class
    nn = NeuralNetwork(input_size=4, hidden_size=8, output_size=3)  # 4 input features, 8 hidden neurons, 3 output classes

    # Train the network
    nn.train(X_train, y_train, epochs=10000, learning_rate=0.1)

    # Test the network
    print("\nPredictions on test data:")
    predictions = nn.forward(X_test)
    print(np.round(predictions, 2))


Epoch 0 - Loss: 0.3457754467173295
Epoch 1000 - Loss: 0.010096481953147015
Epoch 2000 - Loss: 0.009561997898365714
Epoch 3000 - Loss: 0.007546984729913082
Epoch 4000 - Loss: 0.00651173897201844
Epoch 5000 - Loss: 0.006115159620697234
Epoch 6000 - Loss: 0.005923838594124945
Epoch 7000 - Loss: 0.005819867192991113
Epoch 8000 - Loss: 0.005757391648436443
Epoch 9000 - Loss: 0.005716707807811334

Predictions on test data:
[[0.   1.   0.  ]
 [1.   0.01 0.  ]
 [0.   0.   1.  ]
 [0.   1.   0.  ]
 [0.   1.   0.  ]
 [1.   0.01 0.  ]
 [0.   1.   0.  ]
 [0.   0.02 0.98]
 [0.   1.   0.  ]
 [0.   1.   0.  ]
 [0.   0.23 0.77]
 [1.   0.   0.  ]
 [1.   0.01 0.  ]
 [1.   0.01 0.  ]
 [1.   0.01 0.  ]
 [0.   1.   0.  ]
 [0.   0.   1.  ]
 [0.   1.   0.  ]
 [0.   1.   0.  ]
 [0.   0.   1.  ]
 [1.   0.01 0.  ]
 [0.   0.02 0.98]
 [1.   0.01 0.  ]
 [0.   0.   1.  ]
 [0.   0.01 0.99]
 [0.   0.   1.  ]
 [0.   0.   1.  ]
 [0.   0.01 0.99]
 [1.   0.   0.  ]
 [1.   0.01 0.  ]]
